---
title: "informer"
author: "Francisco"
format: html
editor: visual
bibliography: informer.bib
link-citations: True
---

## Percepción de Felicidad en Adultos mayores

#### Introducción

En este último tiempo ya es sabido que los países envejecen más rápido que la tasa de natalidad, por ende, nuestro país no es la excepción y nos transformamos a ser un país más longevo [@moyano-diazFiabilidadValidezConstructo2010] En esta etapa de la vida es de mucha ayuda saber el nivel de satisfacción de la vida del adulto mayor para tener alguna pista de cómo se vive en este país. Con esto quiero decir que: tener la opinión de los individuos que viven en determinado sector da un indicio de cómo se vive en el lugar, más aún si estas opiniones son de un grupo o comunidad del sector.

“La satisfacción de la vida se ha definido como la valoración positiva que la persona hace de su vida en general o de aspectos particulares…" [@schnettlerVariablesQueInfluyen2014] La satisfacción es un “sentimiento” particular y subjetivo y que no refleja lo objetivo del lugar. Los individuos que se encuentran en estado de felicidad(satisfacción) se encuentran distribuidos en las poblaciones de los Países independiente del nivel de desarrollo alcanzado por el País [@moyanodiazBienestarSubjetivoMidiendo2007] si no que se da importancia a las relaciones que la persona crea a lo largo de su vida desde su trabajo a la vida familiar, de sentirse realizado o sentirse un fracaso desde su vida personal. Todo influyen en el nivel de percepción de cada sujeto y puede ser de mucho interés para las próximas generaciones saber cuál es la percepción de satisfacción de los adultos mayores de Chile.

Este trabajo busca comprender cómo se construyen las escalas de satisfacción personal y cuáles son las herramientas que se utilizan a la hora de medir algo tan abstracto como la felicidad. Como lo es la objetividad, es decir, más allá de lo que sujeto percibe como feliz qué es lo que el sujeto en el mundo material posee. según [@rubenardilaCalidadVidaDefinicion2003] “las relaciones de bien material y calidad de vida se han investigado ante todo el contexto de felicidad”. El nivel socio económico de cada individuo depende la calidad de vida que esta persona obtenga, aunque su nivel de percepción sea una, su relación con lo material es indispensable, aunque no es condicionante de su percepción.

Nuestra empresa estará en relacionar ingresos y bienes materiales (datos concretos) con el nivel de percepción de felicidad en los adultos mayores de Chile para entender su comportamiento.
